import type { Metadata } from 'next';
import { supabaseServer } from '@/lib/supabase-server';

type Props = {
  params: Promise<{ id: string }>;
  children: React.ReactNode;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;

  let title = 'Roast My TikTok — Results';
  let description = 'See how AI agents roasted this TikTok video.';

  try {
    const { data } = await supabaseServer
      .from('rmt_roast_sessions')
      .select('overall_score, verdict')
      .eq('id', id)
      .single();

    if (data) {
      title = `Score: ${data.overall_score}/100 — Roast My TikTok`;
      if (data.verdict) {
        description = data.verdict.slice(0, 160);
      }
    }
  } catch { /* fallback metadata */ }

  // OG image is generated by opengraph-image.tsx file convention
  return {
    title,
    description,
    alternates: {
      canonical: `/roast/${id}`,
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
    },
  };
}

export default function RoastLayout({ children }: Props) {
  return <>{children}</>;
}
