import type { Metadata } from 'next';
import AppShell from '@/components/AppShell';

type Props = {
  params: Promise<{ id: string }>;
  children: React.ReactNode;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;

  const title = 'Go Viral - Results';
  const description = 'See how AI agents diagnosed this TikTok video.';

  const ogImageUrl = `/roast/${id}/opengraph-image`;

  // OG image is generated by opengraph-image.tsx file convention
  return {
    title,
    description,
    alternates: {
      canonical: `/roast/${id}`,
    },
    openGraph: {
      title,
      description,
      images: [{ url: ogImageUrl, width: 1200, height: 630, alt: title }],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImageUrl],
    },
  };
}

export default function RoastLayout({ children }: Props) {
  return <AppShell>{children}</AppShell>;
}
