import type { Metadata } from 'next';
import AppShell from '@/components/AppShell';
import { supabaseServer } from '@/lib/supabase-server';

type Props = {
  params: Promise<{ id: string }>;
  children: React.ReactNode;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;

  let title = 'Go Viral - Results';
  let description = 'See how AI agents diagnosed this TikTok video.';

  try {
    const { data } = await supabaseServer
      .from('rmt_roast_sessions')
      .select('overall_score, verdict, filename')
      .eq('id', id)
      .single();

    if (data) {
      title = `My TikTok scored ${data.overall_score}/100 - Go Viral Analysis`;
      if (data.verdict) {
        description = data.verdict.slice(0, 155);
      }
    }
  } catch { /* fallback metadata */ }

  const ogImageUrl = `/roast/${id}/opengraph-image`;

  // OG image is generated by opengraph-image.tsx file convention
  return {
    title,
    description,
    alternates: {
      canonical: `/roast/${id}`,
    },
    openGraph: {
      title,
      description,
      images: [{ url: ogImageUrl, width: 1200, height: 630, alt: title }],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImageUrl],
    },
  };
}

export default function RoastLayout({ children }: Props) {
  return <AppShell>{children}</AppShell>;
}
