import Link from 'next/link';

export default function TermsPage() {
  return (
    <main className="min-h-screen pb-20">
      <div className="max-w-3xl mx-auto px-4 pt-12">
        <Link href="/" className="text-sm text-zinc-500 hover:text-orange-400 transition-colors mb-8 inline-block">
          &larr; Back
        </Link>

        <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-sm text-zinc-500 mb-10">Last updated: March 31, 2026</p>

        <div className="space-y-8 text-sm text-zinc-400 leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using RoastMyTikTok (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. Content Ownership &amp; Upload Policy</h2>
            <p className="mb-3">
              <strong className="text-white">You must only upload videos that you own or have created yourself.</strong> By uploading a video to RoastMyTikTok, you represent and warrant that:
            </p>
            <ul className="list-disc list-inside space-y-1.5 pl-2">
              <li>You are the original creator of the video content.</li>
              <li>You own or have all necessary rights to the video.</li>
              <li>The video does not infringe on any third party&apos;s intellectual property, privacy, or other rights.</li>
              <li>Any TikTok accounts you connect or analyze are your own accounts.</li>
            </ul>
            <p className="mt-3">
              We reserve the right to remove any content and terminate accounts that violate this policy.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. How We Use Your Content</h2>
            <p className="mb-3">
              Videos you upload are processed by AI to generate your roast analysis. By uploading, you explicitly consent to this processing. We do not share, sell, or publicly display your uploaded videos.
            </p>
            <p>
              <strong className="text-white">Video retention:</strong> Uploaded videos are stored in secure cloud storage for the duration of your session and deleted within 30 days of upload. Video frames extracted during AI analysis are processed in real-time and not permanently stored. Analysis results (scores, feedback text) are retained in your account history until you request deletion.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3a. Waitlist &amp; Email Communications</h2>
            <p className="mb-3">
              If you submit your email address to join our waitlist, we will only send launch updates and product announcements if you separately check the optional marketing consent box. You can unsubscribe at any time by clicking the unsubscribe link in any email or by contacting us at{' '}
              <a href="mailto:support@roastmytiktok.com" className="text-orange-400 hover:text-orange-300 transition-colors">
                support@roastmytiktok.com
              </a>.
            </p>
            <p>
              We store waitlist marketing consent choices and cookie-notice acknowledgements in Supabase so we can maintain an auditable record of what you agreed to. We will not sell or share your email address with third parties for marketing purposes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">4. Account Responsibilities</h2>
            <p>
              You are responsible for maintaining the security of your account. You agree not to share your account credentials or use the Service for any unlawful purpose.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. AI-Generated Content</h2>
            <p>
              The roasts, scores, and recommendations provided by the Service are generated by AI and are intended for entertainment and educational purposes. They do not constitute professional advice. Results may vary and are not guaranteed to improve your content performance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">6. Prohibited Uses</h2>
            <ul className="list-disc list-inside space-y-1.5 pl-2">
              <li>Uploading content you do not own or have rights to.</li>
              <li>Using the Service to harass, bully, or target other creators.</li>
              <li>Attempting to reverse-engineer, scrape, or abuse the Service.</li>
              <li>Circumventing any access restrictions or rate limits.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">7. Limitation of Liability</h2>
            <p>
              The Service is provided &ldquo;as is&rdquo; without warranties of any kind. We are not liable for any damages arising from your use of the Service, including but not limited to loss of data, revenue, or content performance outcomes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">8. Changes to Terms</h2>
            <p>
              We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">9. Contact</h2>
            <p>
              Questions about these Terms? Reach out at{' '}
              <a href="mailto:support@roastmytiktok.com" className="text-orange-400 hover:text-orange-300 transition-colors">
                support@roastmytiktok.com
              </a>.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
